### PR TITLE
ok

### PR DESCRIPTION
**Pull request by ArneD4**

### CODE REVIEW

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse @injecti0n

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse @injecti0n

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse @injecti0n

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse @injecti0n

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabalin** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by AtillaiBirNAMUSSUZ** [comment]
Atilla Balin is not a good man,
He always trying to hook girls online, and ask them to visit Belgium. and show himself very pitiful!
at first, he gonna say that he has a trust issue. but trust me! he is totally lying! because he is a very arrogant person. He thinks that he is the greatest.
He likes to use Twitter and using his cat (mojo)'s picture to hook up girls
Twitter is the most active place he is using! when you ask him why he's focusing on Twitter so much? he will answer you he is having political arguments with ppl. that is a lie for sure!
he is flirting with girls on Twitter. trying to fake them to fly to Belgium for his horny!
he also likes to take sex videos. he is a pervert!
he will show you how much he loves his mother. but he's also lying.
when you leave Belgium, he will cry in front of you and say to you how much he gonna miss you. but those are also lies!
this is a fucking fake person!
He is a pervert~
now he is closing all his accounts, Twitter, Facebook, and LinkedIn! 
cause he is shame of what he've done! 
but we should let everyone knows what kind of liar he is! 
just like he said the Turkish government or Erdogan is a liar ! he is also a Kurdish liar  [https://www.linkedin.com/posts/balin-atilla-7394a5201_atilla-b-also-lied-that-beyza-is-a-highschool-activity-6742698499290263552-lV3d](url)
look! how he describe Beyza ! he lied to his girlfriend that she was his highschool friends

**Pull request closed without merging**
