### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by atillabalin**

### CODE REVIEW

**Comment by atillabiraptal** [comment]
this is a Story of a Cheater Atilla Balin, 

in the 2017 summer, Atilla Balin uses the apps call "hello talks" for language exchange.

he met a single woman from HK. 

by then he tried to flirt with this woman. 

the woman told him that, she wasn't looking forward to the relationship, cause she got hurt before. But this Atilla Balin promised he won't hurt her. 

then they fell into each other. 

because of Atilla Balin's situation, she flys to him twice every year. 

2017 Christmas, the first time came to visit him. 

he was very happy. 

things were going well. then this Atilla Balin has changed in 2019 

he started to flirt with girls on Twitter~! and blame back his gf's faults. and keep reminding her that "HE IS NOT A CHEATER! "

2019 AUG Atilla Balin started to cheat with Beyza on Twitter and phone. 

2020 Feb his gf fly again to Belgium. and stuck in Belgium 3 months cause of covid-19 locked down. 

He still kept hiding a lot of things.

2020 Oct his gf found out that he is lying again!

Atilla Balin still being a very rule with her and ask her to find evidence of cheating! still pretending he is a victim. 

2020 Nov finally the truth is shown. and Atilla Balin as his brother to blame his gf. 

2020 Dec Now Atilla Balin is such a shame. all of his lies are under the sun now!

**Comment by atillabiraptal** [comment]
fullsizeoutput_5b28
fullsizeoutput_5b29
lm5EeUteRgC1G5x1BNIbhQ
IkbKo1RnTKG6KA%qodcNkg
fullsizeoutput_5b31
GCibkvRHQgSnz2GP04%s2Q
fullsizeoutput_5b3e
fullsizeoutput_5b3b
fullsizeoutput_5b3a
fullsizeoutput_5b40
fullsizeoutput_5b41
fullsizeoutput_5b3f

**Comment by atillabiraptal** [comment]
this is a Story of a Cheater Atilla Balin, 

in the 2017 summer, Atilla Balin uses the apps call "hello talks" for language exchange.

he met a single woman from HK. 

by then he tried to flirt with this woman. 

the woman told him that, she wasn't looking forward to the relationship, cause she got hurt before. But this Atilla Balin promised he won't hurt her. 

then they fell into each other. 

because of Atilla Balin's situation, she flys to him twice every year. 

2017 Christmas, the first time came to visit him. 

he was very happy. 

things were going well. then this Atilla Balin has changed in 2019 

he started to flirt with girls on Twitter~! and blame back his gf's faults. and keep reminding her that "HE IS NOT A CHEATER! "

2019 AUG Atilla Balin started to cheat with Beyza on Twitter and phone. 

2020 Feb his gf fly again to Belgium. and stuck in Belgium 3 months cause of covid-19 locked down. 

He still kept hiding a lot of things.

2020 Oct his gf found out that he is lying again!

Atilla Balin still being a very rule with her and ask her to find evidence of cheating! still pretending he is a victim. 

2020 Nov finally the truth is shown. and Atilla Balin as his brother to blame his gf. 

2020 Dec Now Atilla Balin is such a shame. all of his lies are under the sun now!

**Comment by atillabiraptal** [comment]
[https://www.linkedin.com/posts/balin-atilla-7394a5201_cheaters-ugcPost-6742694614194540544-6XDU](url)

check out this video guys

**Comment by atillabiraptal** [comment]
[https://www.linkedin.com/posts/balin-atilla-7394a5201_atillab-atilla-balin-activity-6742711602224648192-1sdb](url)

another video of the conversation with Beyza

**Comment by atillabiraptal** [comment]
check it out guys

**Comment by atillabiraptal** [comment]
https://www.linkedin.com/posts/balin-atilla-7394a5201_atillab-atilla-balin-activity-6742711602224648192-1sdb

**Comment by atillabiraptal** [comment]
at first, he said he accepts his girlfriend is a single mom, then he realized he couldn't then he betrayed his girlfriend. When her girlfriend saw a woman called him on a video call. he was lying to her that was his high school friends. and she gonna get marry~~!!! woo.. his girlfriend trusted him. then nowaday she finally finds out all of his lies~
that girl he met on his Twitter randomly~ and just affair with her.
now everyone knows this guy is a cheater
and he also said a lot about his mother~ he is just a two-faced man
for those years from 2017 to 2020, his girlfriend trusted him n fly to Belgium for him many times but in the end, he is cheating and he still blames his girlfriend because she is a single mother. and even though he knew how his girlfriend has been through~ he is doing the same~ and whenever they have argued, he puts the girl past to abuse

**Comment by atillabiraptal** [comment]
https://www.linkedin.com/posts/balin-atilla-7394a5201_atillab-atilla-balin-activity-6742711602224648192-1sdb

check out those video of this @injecti0n disgusting man 
keep saying that he didn't cheat !! but he did very badly and ugly

**Comment by atillabiraptal** [comment]
https://www.linkedin.com/posts/balin-atilla-7394a5201_atillab-atilla-balin-activity-6742711602224648192-1sdb

**Comment by atillabiraptal** [comment]
https://www.linkedin.com/posts/balin-atilla-7394a5201_atillab-atilla-balin-activity-6742711602224648192-1sdb

**Comment by atillabiraptal** [comment]
this is a Story of a Cheater Atilla Balin,

in the 2017 summer, Atilla Balin uses the apps call "hello talks" for language exchange.

he met a single woman from HK.

by then he tried to flirt with this woman.

the woman told him that, she wasn't looking forward to the relationship, cause she got hurt before. But this Atilla Balin promised he won't hurt her.

then they fell into each other.

because of Atilla Balin's situation, she flys to him twice every year.

2017 Christmas, the first time came to visit him.

he was very happy.

things were going well. then this Atilla Balin has changed in 2019

he started to flirt with girls on Twitter~! and blame back his gf's faults. and keep reminding her that "HE IS NOT A CHEATER! "

2019 AUG Atilla Balin started to cheat with Beyza on Twitter and phone.

2020 Feb his gf fly again to Belgium. and stuck in Belgium 3 months cause of covid-19 locked down.

He still kept hiding a lot of things.

2020 Oct his gf found out that he is lying again!

Atilla Balin still being a very rule with her and ask her to find evidence of cheating! still pretending he is a victim.

2020 Nov finally the truth is shown. and Atilla Balin as his brother to blame his gf.

2020 Dec Now Atilla Balin is such a shame. all of his lies are under the sun now!

> https://www.linkedin.com/posts/balin-atilla-7394a5201_atillab-atilla-balin-activity-6742711602224648192-1sdb
> 
> check out those video of this @injecti0n disgusting man
> keep saying that he didn't cheat !! but he did very badly and ugly

**Comment by atillabiraptal** [comment]
#11 he started to cheat on 2019 Aug !
Atilla Balin Started to cheat on 2019 Aug 
this is a Story of a Cheater Atilla Balin,

in the 2017 summer, Atilla Balin uses the apps call "hello talks" for language exchange.

he met a single woman from HK.

by then he tried to flirt with this woman.

the woman told him that, she wasn't looking forward to the relationship, cause she got hurt before. But this Atilla Balin promised he won't hurt her.

then they fell into each other.

because of Atilla Balin's situation, she flys to him twice every year.

2017 Christmas, the first time came to visit him.

he was very happy.

things were going well. then this Atilla Balin has changed in 2019

he started to flirt with girls on Twitter~! and blame back his gf's faults. and keep reminding her that "HE IS NOT A CHEATER! "

2019 AUG Atilla Balin started to cheat with Beyza on Twitter and phone.

2020 Feb his gf fly again to Belgium. and stuck in Belgium 3 months cause of covid-19 locked down.

He still kept hiding a lot of things.

2020 Oct his gf found out that he is lying again!

Atilla Balin still being a very rule with her and ask her to find evidence of cheating! still pretending he is a victim.

2020 Nov finally the truth is shown. and Atilla Balin as his brother to blame his gf.

2020 Dec Now Atilla Balin is such a shame. all of his lies are under the sun now!

**Comment by atillabiraptal** [comment]
tilla Balin is not a good man,
He always trying to hook girls online, and ask them to visit Belgium. and show himself very pitiful!
at first, he gonna say that he has a trust issue. but trust me! he is totally lying! because he is a very arrogant person. He thinks that he is the greatest.
He likes to use Twitter and using his cat (mojo)'s picture to hook up girls
Twitter is the most active place he is using! when you ask him why he's focusing on Twitter so much? he will answer you he is having political arguments with ppl. that is a lie for sure!
he is flirting with girls on Twitter. trying to fake them to fly to Belgium for his horny!
he also likes to take sex videos. he is a pervert!
he will show you how much he loves his mother. but he's also lying.
when you leave Belgium, he will cry in front of you and say to you how much he gonna miss you. but those are also lies!
this is a fucking fake person!
He is a pervert~


vwWu5A0lSAGKvsKR8D8aaQ

**Comment by atillabiraptal** [comment]
Screenshot 2020-12-07 at 4 49 17 AM
Screenshot 2020-12-07 at 4 49 55 AM
Screenshot 2020-12-07 at 4 50 13 AM
Screenshot 2020-12-07 at 4 50 47 AM
Screenshot 2020-12-07 at 4 51 29 AM
Screenshot 2020-12-07 at 4 53 46 AM
Screenshot 2020-12-07 at 4 55 00 AM

**Comment by AtillaiBirNAMUSSUZ** [comment]
@injecti0n Atilla Balin is not a good man,
He always trying to hook girls online, and ask them to visit Belgium. and show himself very pitiful!
at first, he gonna say that he has a trust issue. but trust me! he is totally lying! because he is a very arrogant person. He thinks that he is the greatest.
He likes to use Twitter and using his cat (mojo)'s picture to hook up girls
Twitter is the most active place he is using! when you ask him why he's focusing on Twitter so much? he will answer you he is having political arguments with ppl. that is a lie for sure!
he is flirting with girls on Twitter. trying to fake them to fly to Belgium for his horny!
he also likes to take sex videos. he is a pervert!
he will show you how much he loves his mother. but he's also lying.
when you leave Belgium, he will cry in front of you and say to you how much he gonna miss you. but those are also lies!
this is a fucking fake person!
He is a pervert~
now he is closing all his accounts, Twitter, Facebook, and LinkedIn! 
cause he is shame of what he've done! 
but we should let everyone knows that what kind of liar he is! 
just like he said Turkish government or Erdogan is a liar ! he is also a Kurdish liar

**Comment by AtillaiBirNAMUSSUZ** [comment]
@injecti0nAtilla Balin is not a good man,
He always trying to hook girls online, and ask them to visit Belgium. and show himself very pitiful!
at first, he gonna say that he has a trust issue. but trust me! he is totally lying! because he is a very arrogant person. He thinks that he is the greatest.
He likes to use Twitter and using his cat (mojo)'s picture to hook up girls
Twitter is the most active place he is using! when you ask him why he's focusing on Twitter so much? he will answer you he is having political arguments with ppl. that is a lie for sure!
he is flirting with girls on Twitter. trying to fake them to fly to Belgium for his horny!
he also likes to take sex videos. he is a pervert!
he will show you how much he loves his mother. but he's also lying.
when you leave Belgium, he will cry in front of you and say to you how much he gonna miss you. but those are also lies!
this is a fucking fake person!
He is a pervert~
now he is closing all his accounts, Twitter, Facebook, and LinkedIn! 
cause he is shame of what he've done! 
but we should let everyone knows that what kind of liar he is! 
just like he said Turkish government or Erdogan is a liar ! he is also a Kurdish liar   @injecti0n

**Comment by AtillaiBirNAMUSSUZ** [comment]
Atilla Balin is not a good man,
He always trying to hook girls online, and ask them to visit Belgium. and show himself very pitiful!
at first, he gonna say that he has a trust issue. but trust me! he is totally lying! because he is a very arrogant person. He thinks that he is the greatest.
He likes to use Twitter and using his cat (mojo)'s picture to hook up girls
Twitter is the most active place he is using! when you ask him why he's focusing on Twitter so much? he will answer you he is having political arguments with ppl. that is a lie for sure!
he is flirting with girls on Twitter. trying to fake them to fly to Belgium for his horny!
he also likes to take sex videos. he is a pervert!
he will show you how much he loves his mother. but he's also lying.
when you leave Belgium, he will cry in front of you and say to you how much he gonna miss you. but those are also lies!
this is a fucking fake person!
He is a pervert~
now he is closing all his accounts, Twitter, Facebook, and LinkedIn! 
cause he is shame of what he've done! 
but we should let everyone knows that what kind of liar he is! 
just like he said Turkish government or Erdogan is a liar ! he is also a Kurdish liar  [https://www.linkedin.com/posts/balin-atilla-7394a5201_kurdish-liar-cheater-activity-6743225622132273152-iA0U](url)

**Comment by AtillaiBirNAMUSSUZ** [comment]
@injecti0n Atilla Balin is not a good man,
He always trying to hook girls online, and ask them to visit Belgium. and show himself very pitiful!
at first, he gonna say that he has a trust issue. but trust me! he is totally lying! because he is a very arrogant person. He thinks that he is the greatest.
He likes to use Twitter and using his cat (mojo)'s picture to hook up girls
Twitter is the most active place he is using! when you ask him why he's focusing on Twitter so much? he will answer you he is having political arguments with ppl. that is a lie for sure!
he is flirting with girls on Twitter. trying to fake them to fly to Belgium for his horny!
he also likes to take sex videos. he is a pervert!
he will show you how much he loves his mother. but he's also lying.
when you leave Belgium, he will cry in front of you and say to you how much he gonna miss you. but those are also lies!
this is a fucking fake person!
He is a pervert~
now he is closing all his accounts, Twitter, Facebook, and LinkedIn! 
cause he is shame of what he've done! 
but we should let everyone knows what kind of liar he is! @injecti0n 
just like he said the Turkish government or Erdogan is a liar ! he is also a Kurdish liar  [https://www.linkedin.com/posts/balin-atilla-7394a5201_atilla-b-also-lied-that-beyza-is-a-highschool-activity-6742698499290263552-lV3d](url)
look! how he describe Beyza ! he lied to his girlfriend that she was his highschool friends

**Comment by AtillaiBirNAMUSSUZ** [comment]
this is a disgusting man! Atilla Balin @injecti0n 

he is a very disgusting Kurdish cheater!

Atilla Balin is not a good man,
He always trying to hook girls online, and ask them to visit Belgium. and show himself very pitiful!
at first, he gonna say that he has a trust issue. but trust me! he is totally lying! because he is a very arrogant person. He thinks that he is the greatest.
He likes to use Twitter and using his cat (mojo)'s picture to hook up girls
Twitter is the most active place he is using! when you ask him why he's focusing on Twitter so much? he will answer you he is having political arguments with ppl. that is a lie for sure!
he is flirting with girls on Twitter. trying to fake them to fly to Belgium for his horny!
he also likes to take sex videos. he is a pervert!
he will show you how much he loves his mother. but he's also lying.
when you leave Belgium, he will cry in front of you and say to you how much he gonna miss you. but those are also lies!
this is a fucking fake person!
He is a pervert~
now he is closing all his accounts, Twitter, Facebook, and LinkedIn! 
cause he is shame of what he've done! 
but we should let everyone knows what kind of liar he is! 
just like he said the Turkish government or Erdogan is a liar ! he is also a Kurdish liar  [https://www.linkedin.com/posts/balin-atilla-7394a5201_atilla-b-also-lied-that-beyza-is-a-highschool-activity-6742698499290263552-lV3d](url)
look! how he describe Beyza ! he lied to his girlfriend that she was his highschool friends

**Pull request closed without merging**
